# Generated by Django 5.1.1 on 2025-01-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
